client_config_backend: settings
client_config:
  client_id: "111009476767-rrn5ec748atcgjom3071uurkedsp198r.apps.googleusercontent.com"
  client_secret: "YOUR_CLIENT_SECRET_HERE"

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive